Repository canonical/knative-operators, pull requests merged in 2025-02, with the labels that each got.

#285 refactor(ci): Replace release.yaml with promote.yaml
  .github/workflows/promote.yaml
  .github/workflows/publish.yaml
Labels: Libraries: OK

#287 refactor(ci): Remove duplicate code by merging integration environments
  .github/workflows/ci.yaml
Labels: Libraries: Out of sync

#289 fix(ci): Run charm integration tests in CI
  .github/workflows/ci.yaml
  tox.ini
Labels: Libraries: Out of sync

#295 fix: use charmcraft promote in promote.yaml workflow
  .github/workflows/promote.yaml
Labels: Libraries: Out of sync

#296 chore: integrate operator rock v1.16
  charms/knative-operator/metadata.yaml
Labels: Libraries: Out of sync

#297 chore: integrate webhook rock v1.16
  charms/knative-operator/metadata.yaml
Labels: Libraries: Out of sync

#300 chore: integrate net-istio-webhook:1.16.0-4214206 rock
  charms/knative-serving/src/charm.py
Labels: Libraries: Out of sync, Libraries: OK

#301 chore: integrate net-istio-controller and migrate rocks
  charms/knative-serving/src/charm.py
Labels: Libraries: OK
